apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-svc12
  namespace: my-namespace
spec:
  type: LoadBalancer
  selector:
    app: hello
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  namespace: my-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello 
    spec:
      containers:
        - name: hello
          image: 408881309070.dkr.ecr.us-east-1.amazonaws.com/boobalan-repo29:1.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
